# Generated by Django 4.1.7 on 2023-04-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_alter_product_image_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
