# Generated by Django 4.1.7 on 2023-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('C_Id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=30)),
                ('subscribe_date', models.DateField()),
            ],
        ),
    ]
