# Generated by Django 4.1.7 on 2023-04-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='mail',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribe_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
