# Generated by Django 4.1.7 on 2023-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('C_Id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=30, unique=True)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
