# Generated by Django 4.1.7 on 2023-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribe_date',
            field=models.DateField(),
        ),
    ]
